### ISSUE TITLE
Test in Gran Turismo 2 - Duckstation ... Input Lag changing gears...

### ISSUE THREAD

**Issue by Gron21** [Menkaura81/Anyshift#2]
Looks promising this software! But Im trying last version of Duckstation and Gran Turismo 2 A-Spec Mod 1.1.1, and have a lot of input lag when changing gears, and for some reason when i try to change 5º to 2º sometimes stay in 3º and when i return to 3º it marks 4º...

Im using a USB Shifter named SHH Shifter. it´s plug and play and works well in Win10 x64 with lot of SimRacing games. 📦

**Comment by Menkaura81** [comment]
You can tinker with the press key delay and release key delay timers to got it working.

I will try to make a working profile
