### ISSUE TITLE
Xenia - Xbox 360 emulator

### ISSUE THREAD

**Issue by Gron21** [Menkaura81/Anyshift#3]
Could you make it compatible with Xenia?

It should be interesting with Forza Motorsport/Horizon!

**Comment by Menkaura81** [comment]
Anyshift must be compatible with Xenia using the "SIMULATED KEY PRESSED MODE". To do so, uncheck "memory mode" and set the same keys for upshifting and downshifting in Xenia and Anyshift. Example: If upshift is R1 in the xbox gamepad, configure xenia gamepad R1 button as 's' keyboard key (the same that came by default for upshift in Anyshift). Do the same with 'z' for downshifting. 

I Will try Xenia and comment.

**Comment by Gron21** [comment]
I try that and works! But with some input lag, like near 1 sec between shift and shift... The game was Forza Motorsport 2

**Comment by Menkaura81** [comment]
Change the profile with these values:

press key delay = 0.08
release key delay = 0.1

![image](https://github.com/Menkaura81/Anyshift/assets/65674427/8346fed0-60e2-4ed8-9fc4-6e69cfd92a36)
