### ISSUE TITLE
"Detect Neutral" adds delay to shifting between gears

### ISSUE THREAD

**Issue by itais** [Menkaura81/Anyshift#5]
"Detect Neutral" adds a few tenths of a second (I think) delay to shifting between gears. There is no such delay when shifting from Neutral into a gear.
This is especially problematic when enabling the clutch, since when trying to shift quickly the shifting keystrokes are only sent after I already released the clutch so I get a miss shift.

**Comment by Menkaura81** [comment]
That delay is real (0.3 sec). It's hardcoded into the code. It's there to give you time to change gears without changing into neutral in between. I can make this delay modifiable via the .ini so we can fine tune it

**Comment by itais** [comment]
A modifiable delay will help with quick shifts. 
To eliminate the issue completely, maybe change the behavior so it shifts to a new a gear as soon as it's detected, and only shifts to Neutral after the delay?

**Comment by Menkaura81** [comment]
Maybe. I'm thinking on redoing the shifting logic. I will try some ideas during weekend

**Comment by Menkaura81** [comment]
Just uploaded a release. Don´t expect too much changes, is just optimization, refactoring of the code, but I can´t find a solution for Detect Neutral delay at the moment

**Comment by Menkaura81** [comment]
Problem solved. Changed the delay for a timer. It only changes to neutral when the stick is left in neutral for a certain amount of time. I can´t test that everything works perfect right now. Expect a release tonight or maybe tomorrow

**Comment by Menkaura81** [comment]
Released. Maybe we find some bugs in the wild

**Comment by itais** [comment]
Version 1.0.11 is working well for me, great work! There is no noticeable delay between anymore while shifting between gears with "Detect Neutral" active and the Neutral detection works too.
